#!/bin/bash
#
# Copyright (c) 2011, Alex Westphal. All rights reserved
# Author: Alex Westphal
# Version: 19-Aug-2011
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

file="classes/router/RouterDaemon.class"

echo "Router Daemon"

# Check if help option is set
for i in "$@"
do
	if [ "-h" == $i -o "-help" == $i ]
	then
		echo "
Usage: ./routerd [OPTIONS] [ROUTERID]
    ROUTERID is the router-id of the router to start (not required if a config
    file is specified as an option).
    
Options: 
    -config <config-file> ... The configuration file to use in creating a router
    -group <config-dir> ..... The directory of configuration files to use
                              (starts multiple routers, one for each config file
                              in the specified directory)
    -help ................... Print the help information and exit

		"
		exit
	fi
done


# Check for existence of required class file
if [ ! -r $file ]
then
    printf "Error: Required file (%s) is missing.\nThe project may not have been built.\n" $file
    exit
fi

#Execute the RouterDaemon
java -cp classes router.RouterDaemon $@
